# this script runs R CMD check on the ISRaD package, and data validation tests on all ISRaD data

language: r
jobs:
  include:
    - name: "R package"
      before_install:
      - sudo apt install libgdal-dev
      - cd Rpkg
      r_check_args: --as-cran --run-donttest
    - name: "Data validation"
      install:
      addons:
        apt:
          update: true
          packages:
          - testthat
          - ISRaD
          - openxlsx
          - dplyr
          - tidyr
      script:
      -  cd tests
      -  Rscript ISRaD_data_test.R
